version: '3.7'

services:
  web:
    build: .
    container_name: astro-app
    networks:
      - webnet
    expose:
      - "4321"
    environment:
      - VIRTUAL_HOST=tu-dominio.com
      - VIRTUAL_PORT=4321
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    networks:
      - webnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./nginx-vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - webnet
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx-vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
